modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mixins]]
config = "crafting_accessory.mixins.json"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
logoFile = "icon.png"
description = '''
Equip a crafting table as an accessory to unlock a portable 3x3 crafting grid.
A button shows up in your inventory when the table is equipped.
'''

[[dependencies.${mod_id}]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1.219,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "accessories"
    type = "required"
    versionRange = "[1.1.0-beta,)"
    ordering = "AFTER"
    side = "BOTH"
